import  express from 'express';
import { authToken } from '../../middleware/auth/auth.middleware';
import { bookedRoom } from '../../service/impl/room/bookRoom/bookedRoom.impl';
import { globalValidator } from '../../middleware/globalValidators/globalValidator';
import { validatebookedRoom, validateUpdatedBookedHotel } from '../../validators/validators';
import { showBookedRooms } from '../../service/impl/room/showRooms/showRooms.impl';
import { showBookedRoom } from '../../service/impl/room/showRoom/showRom.impl';
import { updateBookedRoom } from '../../service/impl/room/updateRoom/updateRoom.impl';
const router = express.Router();
router.post('/book-a-new-room', authToken, globalValidator(validatebookedRoom), bookedRoom);
router.get('/show-booked-rooms/:hotelId', authToken, showBookedRooms);
router.get('/show-booked-room/:hotelId/:id', authToken, showBookedRoom);
router.get('/update-booked-room/:hotelId/:id', authToken, globalValidator(validateUpdatedBookedHotel), updateBookedRoom);
export default router;