import express from 'express';
import { authToken } from '../../middleware/auth/auth.middleware';
import { bookHotel } from '../../service/impl/hotel/bookHotel/bookHotel.impl';
import { globalValidator } from '../../middleware/globalValidators/globalValidator';
import { validateBookedHotel, validateUpdatedBookedHotel } from '../../validators/validators';
import { showBookedHotels } from '../../service/impl/hotel/showBookedHotels/showBookedHotels.impl';
import { showBookedHotel } from '../../service/impl/hotel/showBookedHotel/showBookedHotel.impl';
import { editAndUpdateBookedHotel } from '../../service/impl/hotel/updatedBookedHotel/updateBookedHotel.impl';
const router = express.Router();
router.post('/book-hotel', authToken, globalValidator(validateBookedHotel), bookHotel);
router.get('/show-booked-hotels', authToken, showBookedHotels);
router.get('/show-booked-hotel/:id', authToken, showBookedHotel);
router.put('/update-booked-hotel/:id', authToken, globalValidator(validateUpdatedBookedHotel), editAndUpdateBookedHotel);
export default router;