import express from 'express';
import { register } from '../../service/impl/auth/register/register.impl';
import { authToken } from '../../middleware/auth/auth.middleware';
import { globalValidator } from '../../middleware/globalValidators/globalValidator';
import { validateLoginUser, validateRegisterUser, validateUpdatedUser } from '../../validators/validators';
import { login } from '../../service/impl/auth/login/login.impl';
import { fetchAllUsers } from '../../service/impl/auth/fetchAllUsers/fetchAllUsers.impl';
import { fetchOneUser } from '../../service/impl/auth/fetchUser/fetchUser.impl';
import { editAndUpdateOneUser } from '../../service/impl/auth/updateUser/updateUser.impl';
import { deleteOneUser } from '../../service/impl/auth/deleteAccount/deleteUser.impl';
const router = express.Router();
router.post('/register', authToken, globalValidator(validateRegisterUser), register);
router.post('/login', authToken, globalValidator(validateLoginUser), login);
router.get('/all-users', authToken, fetchAllUsers);
router.get('/one-user/:id', authToken, fetchOneUser);
router.put('update-user/:id', authToken, globalValidator(validateUpdatedUser), editAndUpdateOneUser);
router.delete('/delete-user/:id', authToken, deleteOneUser);
export default router;