import express from 'express';
import { register } from '../../service/impl/auth/register/register.impl';
import { authToken } from '../../middleware/auth/auth.middleware';
import { globalValidator } from '../../middleware/globalValidators/globalValidator';
import { validateLoginUser, validateRegisterUser } from '../../validators/validators';
import { login } from '../../service/impl/auth/login/login.impl';
const router = express.Router();
router.post('/register', authToken, globalValidator(validateRegisterUser), register);
router.post('/login', authToken, globalValidator(validateLoginUser), login);
export default router;