import express from 'express';
import { authToken } from '../../middleware/auth/auth.middleware';
import { newBooking } from '../../service/impl/booking/newBooking/newBooking.impl';
import { globalValidator } from '../../middleware/globalValidators/globalValidator';
import { validateNewBooking, validateUpdatedBooking } from '../../validators/validators';
import { showBookings } from '../../service/impl/booking/showBookings/showBookings.impl';
import { showBooking } from '../../service/impl/booking/showBooking/showBooking.impl';
import { editAndUpdateBooking } from '../../service/impl/booking/updateBooking/updateBooking.impl';
import { deleteBooking } from '../../service/impl/booking/deleteBooking/deleteBooking.impl';
const router = express.Router();
router.post('/new-booking/', authToken, globalValidator(validateNewBooking), newBooking);
router.get('/show-bookings', authToken, showBookings);
router.get('/show-booking/:id', authToken, showBooking);
router.put('/update-booking/:id', authToken, globalValidator(validateUpdatedBooking), editAndUpdateBooking);
router.delete('/delete-booking/:id', authToken, deleteBooking);
export default router;