import express from 'express';
import { authToken } from '../../middleware/auth/auth.middleware';
import { addANewCustomer } from '../../service/impl/customer/newCustomer/customer.impl';
import { globalValidator } from '../../middleware/globalValidators/globalValidator';
import { validateCustomerRegistration, validateUpdatedCustomerRegistration } from '../../validators/validators';
import { showCustomers } from '../../service/impl/customer/showCustomers/showCustomers.impl';
import { showCustomer } from '../../service/impl/customer/showCustomer/showCustomer.impl';
import { editAndUpdateCustomer } from '../../service/impl/customer/updateCustomer/updateCustomer.impl';
const router = express.Router();
router.post('/add-new-customer', authToken, globalValidator(validateCustomerRegistration), addANewCustomer);
router.get('/show-customers', authToken, showCustomers);
router.get('/show-customer/:id', authToken, showCustomer);
router.put('/update-customer/:id', authToken, globalValidator(validateUpdatedCustomerRegistration), editAndUpdateCustomer);
export default router;