import express from 'express';
import { authToken } from '../../middleware/auth/auth.middleware';
import { sendFAQ } from '../../service/impl/faq/sendFAQ/sendFAQ.impl';
import { globalValidator } from '../../middleware/globalValidators/globalValidator';
import { validateFAQ } from '../../validators/validators';
import { showFAQs } from '../../service/impl/faq/showFAQs/showFAQs.impl';
import { showFAQ } from '../../service/impl/faq/showFAQ/showFAQ.impl';
const router = express.Router();
router.post('/send-faq', authToken, globalValidator(validateFAQ), sendFAQ);
router.get('/show-faqs', authToken, showFAQs);
router.get('/show-faq/:id', authToken, showFAQ);
export default router;