import express from 'express';
import { authToken } from '../../middleware/auth/auth.middleware';
import { sendFAQ } from '../../service/impl/faq/sendFAQ/sendFAQ.impl';
import { globalValidator } from '../../middleware/globalValidators/globalValidator';
import { validateFAQ } from '../../validators/validators';
import { showFAQs } from '../../service/impl/faq/showFAQs/showFAQs.impl';
import { showFAQ } from '../../service/impl/faq/showFAQ/showFAQ.impl';
import { updateFAQ } from '../../service/impl/faq/updateFAQ/updateFAQ.impl';
const router = express.Router();
router.post('/send-question', authToken, globalValidator(validateFAQ), sendFAQ);
router.get('/show-questions', authToken, showFAQs);
router.get('/show-question/:id', authToken, showFAQ);
router.put('/update-question/:id', authToken, updateFAQ);
export default router;